language: node_js
sudo: false
node_js:
  - '5'
  - '6'

before_script:
  - npm install -g travis-build-publisher

before_deploy:
  - publish-build

deploy:
  provider: npm
  edge:
    source: mamont/dpl
    branch: add-npm-tags
  email: ${AUTHOR_EMAIL_ADDR}
  api_key: ${AUTHOR_NPM_API_KEY}
  skip_cleanup: true
  tag: "dev"
  on:
    branch: master
