language: node_js
sudo: false
node_js:
  - '5'
  - '6'

deploy:
  provider: npm
  edge:
    source: mamont/dpl
    branch: add-npm-tags
  email: ${AUTHOR_EMAIL_ADDR}
  api_key: ${AUTHOR_NPM_API_KEY}
  skip_cleanup: true
  tag: "alpha"
  on:
    branch: master
