language: node_js
sudo: false
node_js:
  - '5'
  - '6'

deploy:
  provider: npm
  edge:
    source: mamont/dpl
    branch: add-npm-tags
  email: vasya@nowhere.com
  api_key: "xxxxx"
  skip_cleanup: true
  tags: "alpha"
  on:
    branch: master
